#!/bin/bash


if [[ ! -d "$HOME/.nvim_setup.loaded" ]]; then
  echo "Cloning nvim setup"

  git clone git@github.com:tijesunimi-peters/nvim.git $HOME/.nvim_setup

  cp -r $HOME/.nvim_setup/lua $HOME/.config/nvim     
  cp $HOME/.nvim_setup/init.lua $HOME/.config/nvim/init.lua     
  cp $HOME/.nvim_setup/.stylua.toml $HOME/.config/nvim/.stylua.toml    

  touch "$HOME/.nvim_setup.loaded"

fi
